---
openapi: 3.1.0
info:
  title: Trello Proxy API
  version: 1.0.0
  description: Прокси API для управления Trello через Railway
servers:
  - url: https://mindexecutor-production.up.railway.app
paths:
  /boards:
    get:
      operationId: getBoards
      summary: Получить доски Trello
      responses:
        '200':
          description: OK
  # Остальной YAML можно дозаполнить вручную при необходимости